---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.homeoffice.wal-mart.com/library/oskoss/pks     
    insecure_registries: ["harbor.homeoffice.wal-mart.com"]

inputs:
  - name: peters-pipelines
  - name: kube-config

run:
  path: peters-pipelines/kubernetes/tasks/setup-tiller/task.sh